# Generated by Django 3.0.8 on 2020-08-02 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_case', models.DateField(null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('clinician', models.CharField(max_length=200, null=True)),
                ('veterinary', models.CharField(max_length=200, null=True)),
                ('key_words', models.CharField(max_length=200, null=True)),
                ('diagnosis', models.CharField(max_length=200, null=True)),
                ('animal_name', models.CharField(max_length=200, null=True)),
                ('signalment', models.CharField(max_length=200, null=True)),
                ('complaint', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='resource/files')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='resource/pictures')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
            ],
        ),
    ]
