# Generated by Django 3.0.8 on 2020-08-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='animal_name',
            new_name='name_of_animal',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='veterinary',
            new_name='veterinary_clinic',
        ),
    ]
